[project]
name = "django-example"
version = "0.1.0"
description = "An example django project"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "black>=24.10.0",
    "django>=5.1.2",
]
